# Generated by Django 5.2.1 on 2025-05-18 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=50, null=True)),
                ('nit', models.FloatField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_producto', models.CharField(max_length=100)),
                ('cantidad_producto', models.IntegerField()),
                ('valor_producto', models.CharField(max_length=30)),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxiaseo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id_entrada_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('fecha_entrada', models.DateField()),
                ('cantidad_producto', models.IntegerField()),
                ('costo_entrada', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxiaseo.producto')),
                ('id_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maxiaseo.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=30)),
                ('id_administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maxiaseo.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_Creacion', models.DateField()),
                ('estado_pedido', models.CharField(max_length=30)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxiaseo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxiaseo.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxiaseo.producto')),
            ],
            options={
                'unique_together': {('id_pedido', 'id_producto')},
            },
        ),
    ]
