# Generated by Django 5.2.1 on 2025-05-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxiaseo', '0002_alter_pedido_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='Categoria',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
    ]
