# Generated by Django 5.2.1 on 2025-06-13 04:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxiaseo', '0003_alter_categoria_table_alter_producto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venta',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maxiaseo.pedido'),
        ),
    ]
