# Generated by Django 5.2.1 on 2025-06-13 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxiaseo', '0004_venta_fecha_venta_venta_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproductos',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='maxiaseo.pedido'),
        ),
    ]
