# Generated by Django 5.2.1 on 2025-06-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxiaseo', '0005_alter_pedidoproductos_id_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradaproducto',
            old_name='nombre_producto',
            new_name='descripcion',
        ),
    ]
