# Generated by Django 5.2.1 on 2025-06-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxiaseo', '0006_rename_nombre_producto_entradaproducto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproducto',
            name='costo_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
