# Generated by Django 5.2.1 on 2025-06-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxiaseo', '0007_alter_entradaproducto_costo_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='valor_producto',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
