# Generated by Django 5.2.1 on 2025-06-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxiaseo', '0008_alter_producto_valor_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo',
            field=models.CharField(default='efectivo', max_length=50),
        ),
    ]
