# Generated by Django 5.2.1 on 2025-06-19 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxiaseo', '0009_pedido_metodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaproducto',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='costo_entrada',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='id_producto',
        ),
        migrations.CreateModel(
            name='EntradaProductoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='maxiaseo.entradaproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxiaseo.producto')),
            ],
            options={
                'unique_together': {('entrada', 'producto')},
            },
        ),
    ]
