# Generated by Django 5.2.1 on 2025-06-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxiaseo', '0011_estado_alter_pedido_estado_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveField(
            model_name='historialestadopedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='historialestadopedido',
            name='pedido',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='HistorialEstadoPedido',
        ),
    ]
